### ISSUE TITLE
Image is occasionally not inside MessageEmbed when RandomEmote is invoked

### ISSUE THREAD

**Issue by jdmremi** [jdmremi/Emotes-TS#5]
Whenever `..randomemote` is invoked, sometimes the image is separate from the embed, and not inside of the embed itself. (See below)

I'm not sure what causes this, as I seem to be following the documentation properly for attaching local files to embeds.

Edit: It appears that if the file name has an `@` "(at) symbol" in it, then it will not work. 

[Link to RandomEmote.ts](https://github.com/Vezqi/Emotes-TS/blob/master/commands/RandomEmote.ts)

![image](https://user-images.githubusercontent.com/27045730/123737897-a7457200-d858-11eb-8276-135c4c3d06fa.png)

**Comment by Vezqi** [comment]
[This](https://github.com/Vezqi/Emotes-TS/commit/f87b202ed15eac6938d7e5c4493e572907f80cc6) commit fixes this issue. Images were not attached when the filename contained `@`.
